### PR TITLE
Add black linter workflow

### LINKED ISSUE #15: Add the black linter workflow
Add the black linter to ensure proper and uniform linting of the codebase. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the black linter in GitHub actions.

I would like to work on this as a part of GSSoC 23.

### PR DESCRIPTION
**Pull request by metabiswadeep**
Fixes #15
Added the black linter workflow

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@abhijeet141 Could you please merge this PR if no changes are necessary?

**Comment by metabiswadeep** [comment]
@abhijeet141

**Comment by metabiswadeep** [comment]
@abhijeet141

**Comment by metabiswadeep** [comment]
@abhijeet141 Please merge this

**Comment by abhijeet141** [comment]
Great Work 🚀 Sorry for delay

**Pull request merged**
