### PR TITLE
validation and error handling

### PR DESCRIPTION
**Pull request by okaditya84**
As I previously opened an issue, which was assigned to me.
I am pushing the updated code with proper error handling and reducing ambiguity in assignment of dataframe by storing it in a separate variable.
Kindly let me have the updates for any other changes or modifications.

### CODE REVIEW

**Comment by abhijeet141** [comment]
Hello @okaditya84 I have reviewed your PR and  I noticed a few changes in the code that need to be rectified. 
1. In the code, you used "model" instead of "better_model" when making predictions and initially better_model is defined
2. Please check that you use the correct variable names as defined in the cropInfo class as there are mismatch
I kindly request you to test the code in your local environment and ensure that all errors are resolved and please provide a screenshot of the response to verify that the code is functioning correctly.

**Comment by okaditya84** [comment]
> Hello @okaditya84 I have reviewed your PR and I noticed a few changes in the code that need to be rectified.
> 
> 1. In the code, you used "model" instead of "better_model" when making predictions and initially better_model is defined
> 2. Please check that you use the correct variable names as defined in the cropInfo class as there are mismatch
>    I kindly request you to test the code in your local environment and ensure that all errors are resolved and please provide a screenshot of the response to verify that the code is functioning correctly.

Hey @abhijeet141, I reviewed the code. But as it happens I'm seeing the variable name as "better_model" and not "model". Here is the proof of confidence.
Screenshot 2023-05-25 111242
Screenshot 2023-05-25 111231

**Comment by abhijeet141** [comment]
@okaditya84 Yes the name of variable is better_model but you changed to model here - 
image

**Comment by okaditya84** [comment]
Hey Abhijeet,
I am Aditya.
I made a new issue regarding this update of the main.py file as the old
issue got closed because I had to delete the repository as the codes had
some conflicts. Kindly assign me the new issue I created.
Thanks in anticipation.

**Pull request closed without merging**
