### PR TITLE
Improve Error Handling in API Endpoints

### PR DESCRIPTION
**Pull request by ayush-09**
#16

### CODE REVIEW

**Comment by ayush-09** [comment]
@abhijeet141 Please review my PR

**Comment by ayush-09** [comment]
@abhijeet141 Please check

**Comment by abhijeet141** [comment]
great work 🚀

**Comment by abhijeet141** [comment]
@ayush-09 I need to revert this PR as deployment is getting failed

**Comment by abhijeet141** [comment]
image
I think this has been repeated twice in the code you need to fix this

**Pull request merged**
